/// corec — the core compiler.
///
/// Reads .aski files from a directory, emits Rust source
/// with rkyv derives. The bootstrap seed.
///
/// Usage: corec <input-dir> <output-file>

mod lex;
#[cfg(test)]
mod lex_tests;
mod parse;
#[cfg(test)]
mod parse_tests;
mod codegen;

use std::fs;
use std::path::Path;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 3 {
        eprintln!("usage: corec <input-dir> <output-file>");
        std::process::exit(1);
    }

    let core_dir = Path::new(&args[1]);
    let out_path = Path::new(&args[2]);

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).expect("failed to create output directory");
    }

    let mut all_output = String::new();
    all_output.push_str("// Generated by corec from .aski files.\n");
    all_output.push_str("// Do not edit — regenerate with `corec`.\n\n");

    let mut files: Vec<_> = fs::read_dir(core_dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {}", core_dir.display(), e))
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map(|x| x == "aski").unwrap_or(false))
        .collect();

    files.sort_by_key(|e| e.path());

    for entry in &files {
        let path = entry.path();
        let source = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {}", path.display(), e));

        let tokens = lex::lex(&source)
            .unwrap_or_else(|e| panic!("lex error in {}: {}", path.display(), e));

        let module = parse::parse_file(tokens)
            .unwrap_or_else(|e| panic!("parse error in {}: {}", path.display(), e));

        let rust = codegen::emit_module(&module);

        all_output.push_str(&format!("// — from {} —\n\n", path.display()));
        all_output.push_str(&rust);
        all_output.push('\n');

        eprintln!("corec: {} → {} domains", path.display(), module.domains.len());
    }

    fs::write(out_path, &all_output)
        .unwrap_or_else(|e| panic!("failed to write {}: {}", out_path.display(), e));

    eprintln!("corec: wrote {}", out_path.display());
}
